# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_auto_20160724_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='clue',
            name='clue_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clue',
            name='clue_text',
            field=models.TextField(default=b''),
        ),
    ]
